export const adminHeaderLinks = [
  {
    label: "Translation",
    imgURL: "/icons/translation.png",
  },
  {
    label: "Notifications",
    imgURL: "/icons/notifications.png",
  },
];

export const adminSidebarTopLinks = [
  {
    label: "Dashboard",
    route: "/dashboard",
    imgURL: "/icons/dashboard.png",
  },
  {
    label: "Documents",
    route: "/dashboard/documents",
    imgURL: "/icons/dashboard.png",
  },
  {
    label: "Billing",
    route: "/dashboard/billing",
    imgURL: "/icons/billing.png",
  },
];

export const adminSidebarBottomLinks = [
  {
    label: "Settings",
    route: "/dashboard/setting",
    imgURL: "/icons/setting.png",
  },
];
export const bannerImages1 = [
  { src: "/images/youcan.png", alt: "youcan" },
  { src: "/images/shopify.png", alt: "shopify" },
  { src: "/images/woo-commerce.png", alt: "woo commerce" },
];

export const footerLinks = [
  // { route: "/about-us", label: "About Us" },
  // { route: "/contact-us", label: "Contact Us" },
  // { route: "/privacy-policy", label: "Policies" },
  // { route: "/how-it-works", label: "How it works" },
  // { route: "/pricing", label: "Pricing" },
  // { route: "/waitlist", label: "Waitlist" },
];

export const navbarLinks = [
  { route: "/about-us", label: "About" },
  { route: "/pricing", label: "Pricing" },
    { route: "/privacy-policy", label: "Policies" },

  { route: "/contact-us", label: "Contact us" },
];

export const svgLandingPage = [
  "/svg/vercel.svg",
  "/svg/bucket.svg",
  "/svg/mobbin.svg",
  "/svg/statry.svg",
  "/svg/springer.svg",
  "/svg/addEvent.svg",
  "/svg/murmur.svg",
  "/svg/replicate.svg",
];

export const pricingPlans = [
  {
    pricing: [
      {
        name: "CDN locations",
        Basic: "100",
        Plus: "100",
        Advanced: "600+",
        Enterprise: "600+",
      },
      {
        name: "Storage",
        Basic: "10 GB",
        Plus: "50 GB",
        Advanced: "300 GB",
        Enterprise: "unlimited",
      },
      {
        name: "Bandwidth",
        Basic: "10 GB",
        Plus: "50 GB",
        Advanced: "300 GB",
        Enterprise: "unlimited",
      },
      {
        name: "Processing",
        Basic: "1 Hour",
        Plus: "5 Hours",
        Advanced: "30 Hours",
        Enterprise: "unlimited",
      },
      {
        name: "Images",
        Basic: "~6,000",
        Plus: "~30,000",
        Advanced: "~180,000",
        Enterprise: "unlimited",
      },
      {
        name: "Documents",
        Basic: "~12,000",
        Plus: "~60,000",
        Advanced: "~360,000",
        Enterprise: "unlimited",
      },
      {
        name: "Video thumbnails",
        Basic: "~300",
        Plus: "~1,500",
        Advanced: "~10,000",
        Enterprise: "unlimited",
      },
      {
        name: "Videos",
        Basic: "40 Encoding Mins",
        Plus: "200 Encoding Mins",
        Advanced: "1,200 Encoding Mins",
        Enterprise: "unlimited",
      },
      {
        name: "Audio",
        Basic: "80 Encoding Mins",
        Plus: "400 Encoding Mins",
        Advanced: "2,400 Encoding Mins",
        Enterprise: "unlimited",
      },
      {
        name: "Monthly uploads",
        Basic: "20,000",
        Plus: "100,000",
        Advanced: "500,000",
        Enterprise: "unlimited",
      },
      {
        name: "Max upload size",
        Basic: "50 MB",
        Plus: "500 MB",
        Advanced: "100 GB",
        Enterprise: "unlimited",
      },
      {
        name: "Monthly downloads",
        Basic: "unlimited",
        Plus: "unlimited",
        Advanced: "unlimited",
        Enterprise: "unlimited",
      },
      {
        name: "Upload widget",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "File storage",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "File processing",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Traffic management",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Rate limiting",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Traffic limiting",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "File size limiting",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "TTLs / Expiring links",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "IP Blacklisting",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Usage monitoring",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "SSL (HTTPS)",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Bytescale SDKs",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Lightweight",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Adaptive chunking",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Cancellable uploads",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Progress reporting",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Bytescale Storage API",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Upload files",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "List files",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Folders",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Metadata & tags",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Bytescale Media APIs",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Image Processing API",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Video Processing API",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Audio Processing API",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Bytescale CDN",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Media optimization",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Origin shielding",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "DDoS protection",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Edge caching",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Permanent caching",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Built-in Storage",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "External Storage",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "HTTP Reverse Proxy",
        Basic: true,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "AWS S3",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Cloudflare R2",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "DigitalOcean Spaces",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Google Storage",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Authenticated uploads",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Authenticated downloads",
        Basic: false,
        Plus: true,
        Advanced: true,
        Enterprise: true,
      },

      {
        name: "Support via Email",
        Basic: false,
        Plus: false,
        Advanced: true,
        Enterprise: true,
      },
      {
        name: "Support via Slack",
        Basic: false,
        Plus: false,
        Advanced: true,
        Enterprise: true,
      },

      {
        name: "Custom domain",
        Basic: false,
        Plus: false,
        Advanced: false,
        Enterprise: true,
      },
      {
        name: "Upload acceleration",
        Basic: false,
        Plus: false,
        Advanced: false,
        Enterprise: true,
      },
    ],
  },
];
